name = "main"
description = "A landing page theme for Matthias personal website."
license = "MIT"

[extra]
greeting = "hej, hej!"

iam = "I am"

links = [
    { title = "E-Mail", url = "mailto:hello_website@mail.matthias-zepper.de", iconset = "fas", icon = "envelope" },
    { title = "GitHub", url = "https://github.com/matthiaszepper", icon = "github" },
    { title = "Twitter", url = "https://twitter.com/matthiaszepper", icon = "twitter" }
]

[extra.author]
name = "Matthias"

[author]
name = "Matthias Zepper"
homepage = "https://www.matthias-zepper.de"

